import { TradeWindowToken } from "@/types";

export const token: TradeWindowToken[] = [
  {
    id: "1",
    name: "Mexican Token",
    symbol: "MXN",
    fiat: "CETES",
    icon: "/placeholder.svg",
    amount: 100_000,
    ratio: 0.8,
  },
  {
    id: "2",
    name: "Sound Token",
    symbol: "SND",
    fiat: "EUROB",
    icon: "/placeholder.svg",
    amount: 23_000,
    ratio: 0.3,
  },
];

export const stablecoins: TradeWindowToken[] = [
  {
    id: "usdt",
    name: "Tether",
    icon: "https://cryptologos.cc/logos/tether-usdt-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDT",
  },
  {
    id: "usdc",
    name: "USD Coin",
    icon: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDC",
  },
  {
    id: "dai",
    name: "Dai",
    icon: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "DAI",
  },
  {
    id: "busd",
    name: "Binance USD",
    icon: "https://cryptologos.cc/logos/binance-usd-busd-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "BUSD",
  },
  {
    id: "ust",
    name: "TerraUSD",
    icon: "https://cryptologos.cc/logos/terrausd-ust-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "UST",
  },
  {
    id: "pax",
    name: "Pax Dollar",
    icon: "https://cryptologos.cc/logos/paxos-standard-pax-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "PAX",
  },
  {
    id: "tusd",
    name: "TrueUSD",
    icon: "https://cryptologos.cc/logos/trueusd-tusd-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "TUSD",
  },
  {
    id: "gusd",
    name: "Gemini Dollar",
    icon: "https://cryptologos.cc/logos/gemini-dollar-gusd-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "GUSD",
  },
  {
    id: "usdp",
    name: "Pax Dollar",
    icon: "https://cryptologos.cc/logos/pax-dollar-usdp-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDP",
  },
  {
    id: "frax",
    name: "Frax",
    icon: "https://cryptologos.cc/logos/frax-frax-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "FRAX",
  },
];