import { AssetProp, TradeWindowToken } from "@/types";

export const token: (AssetProp | TradeWindowToken)[] = [
  {
    id: "1",
    name: "Mexican Token",
    symbol: "MXN",
    fiat: "CETES",
    price: 1.2,
    amount: 100_000,
    image: "/placeholder.svg",
    change: 0.5,
    yield: 0.1,
    initialInvestment: 120_000,
    currentInvestment: 130_000,
    nextYield: 0.12,
    tnx: "txn12345",
  },
  {
    id: "2",
    name: "Sound Token",
    symbol: "SND",
    fiat: "EUROB",
    price: 0.8,
    amount: 23_000,
    image: "/placeholder.svg",
    change: -0.2,
    yield: 0.05,
    initialInvestment: 18_400,
    currentInvestment: 17_000,
    nextYield: 0.06,
    tnx: "txn67890",
  },
  {
    id: "3",
    name: "Quantum Coin",
    symbol: "QTC",
    fiat: "USD",
    price: 150,
    amount: 500,
    image: "/placeholder.svg",
    change: 1.5,
    yield: 0.2,
    initialInvestment: 75_000,
    currentInvestment: 90_000,
    nextYield: 0.25,
    tnx: "txn54321",
  },
  {
    id: "4",
    name: "Solar Token",
    symbol: "SLR",
    fiat: "USD",
    price: 0.5,
    amount: 50_000,
    image: "/placeholder.svg",
    change: 0.3,
    yield: 0.15,
    initialInvestment: 25_000,
    currentInvestment: 30_000,
    nextYield: 0.18,
    tnx: "txn98765",
  },
  {
    id: "5",
    name: "Crypto Nova",
    symbol: "CNV",
    fiat: "EUR",
    price: 10,
    amount: 10_000,
    image: "/placeholder.svg",
    change: -0.1,
    yield: 0.08,
    initialInvestment: 100_000,
    currentInvestment: 95_000,
    nextYield: 0.09,
    tnx: "txn11223",
  },
];

export const stablecoins: TradeWindowToken[] = [
  {
    id: "usdt",
    name: "Tether",
    icon: "https://cryptologos.cc/logos/tether-usdt-logo.png",
    amount: 50000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDT",
  },
  {
    id: "usdc",
    name: "USD Coin",
    icon: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
    amount: 10000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDC",
  },
  {
    id: "dai",
    name: "Dai",
    icon: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png",
    amount: 1000,
    ratio: 1,
    fiat: "USD",
    symbol: "DAI",
  },
  {
    id: "busd",
    name: "Binance USD",
    icon: "https://cryptologos.cc/logos/binance-usd-busd-logo.png",
    amount: 3000,
    ratio: 1,
    fiat: "USD",
    symbol: "BUSD",
  },
  {
    id: "ust",
    name: "TerraUSD",
    icon: "https://cryptologos.cc/logos/terrausd-ust-logo.png",
    amount: 1300,
    ratio: 1,
    fiat: "USD",
    symbol: "UST",
  },
  {
    id: "pax",
    name: "Pax Dollar",
    icon: "https://cryptologos.cc/logos/paxos-standard-pax-logo.png",
    amount: 2000,
    ratio: 1,
    fiat: "USD",
    symbol: "PAX",
  },
  {
    id: "tusd",
    name: "TrueUSD",
    icon: "https://cryptologos.cc/logos/trueusd-tusd-logo.png",
    amount: 12000,
    ratio: 1,
    fiat: "USD",
    symbol: "TUSD",
  },
  {
    id: "gusd",
    name: "Gemini Dollar",
    icon: "https://cryptologos.cc/logos/gemini-dollar-gusd-logo.png",
    amount: 1300,
    ratio: 1,
    fiat: "USD",
    symbol: "GUSD",
  },
  {
    id: "usdp",
    name: "Pax Dollar",
    icon: "https://cryptologos.cc/logos/pax-dollar-usdp-logo.png",
    amount: 61000,
    ratio: 1,
    fiat: "USD",
    symbol: "USDP",
  },
  {
    id: "frax",
    name: "Frax",
    icon: "https://cryptologos.cc/logos/frax-frax-logo.png",
    amount: 24000,
    ratio: 1,
    fiat: "USD",
    symbol: "FRAX",
  },
];
